### ISSUE TITLE
assert doesn't throw the actual errors if connection failed

### ISSUE THREAD

**Issue by jacobtipp** [dwyl/hapi-postgres-connection#15]
I wasn't sure if this was intentional or not on [line 13](https://github.com/dwyl/hapi-postgres-connection/blob/master/index.js#L13). I created a new virtual machine and was having some complications with my local postgres installation. The problem was I wasn't getting any proper error messages with the current assertion because it never returns the error coming from the callback. 

If this wasn't intentional I can make a pull request and clean this up a little bit with some tests.

**Comment by nelsonic** [comment]
@traducer you are 100% correct. The assert is simply designed to let the developer know _where_ the error is being thrown. It has not been an issue for us, but we _could_ make it more _informative_...
