### ISSUE TITLE
How to access the client in another plugin

### ISSUE THREAD

**Issue by jay-meister** [dwyl/hapi-postgres-connection#19]
I have been trying to access the client exposed by hapi-postgress-connection in another plugin registered _after_ hpc.

```
var tags = require('./tags');
server.register([HapiPostgresConnection, { register: tags, options: {hpc: HapiPostgresConnection}}
```

I want to use the client in the tags plugin, but i get an error:
```
var register = function (server, options, next) {
  console.log('in tags plugin');
  console.log(options.hpc.getCon());

  return next();
};
```

Which gives the error 
```
/Users/jmurphy/web/tags-system/node_modules/hapi-postgres-connection/index.js:56
  return { client: PG_CON[0].client, done: PG_CON[0].done };
                            ^
TypeError: Cannot read property 'client' of undefined
```

I think the hpc plugin hasn't had time to create the client and add it to the PG_CON array.

Is it a problem with my implementation or do you know of  a way around this? I have seen hapi module glue but I want to know if there is an easier way.

**Comment by nelsonic** [comment]
@JMurphyWeb _thankyou_ for pointing out that the documentation is _sorely lacking_ in this module ... 
@roryc89 added this functionality a _while_ back and it's being _used_ in a couple of our (_sadly_) #ClosedSource Client Projects ...

 in a different plugin or where the `request` object is unavailable:

``` js
var HPC = require('hapi-postgres-connection');
HPC.getCon().client.query('YOUR SQL QUERY HERE', (error, result) => {
 // do things!
}
```

If you have time, please PR an update to the Readme to reflect this functionality. thanks!

**Comment by jay-meister** [comment]
The `getCon()` is in the README, and I have used it in the code snippet..

What you have done is basically the same as what I have done, and it would still give me the same error as the client hasn't had time to be initialised by the time the next plugin has registered. I have got around the problem for now by following your pattern.

```
if (!runOnce){
  runOnce = true;
  // do db initialisation stuff
}
```

I will update if I find a better solution

**Comment by george-iuriet** [comment]
@JMurphyWeb @nelsonic could you please explain this workaround? I need to access the db inside socket.io handlers and I get the same error. Also, would updating to hapi 17 help mitigate this issue? Thanks.

**Comment by jay-meister** [comment]
Hi @george-iuriet I have just had a look through the code of the projects that were using this module and the `runOnce` workaround seems to have been removed.

I'm sorry I can't remember how this all tied together at the time, but [this commit](https://github.com/postgres-plugin/tags-system/pull/27/files) seems to add the `runOnce`, which was then removed at a later date.

With discussion on it [here](https://github.com/postgres-plugin/tags-system/issues/25#issuecomment-258890081)

Sorry I couldn't be of more use.
