### ISSUE TITLE
Tests take ages to actually close

### ISSUE THREAD

**Issue by jay-meister** [dwyl/hapi-postgres-connection#21]
I have a teardown test:

```
var tape = require('tape');
var server = require('../example/server.js');

tape('check that plugin is being attached to the request object', function (t) {
  server.inject({
    method: 'GET',
    url: '/'
  }, function (result) {
    t.equal(result.statusCode, 200,
      'Looks for the endpoint where method is attached to request object.');
    t.end();
  });
});

tape('teardown', function (t) {
  server.stop();
  t.end();
});

```

The test hangs for about 1 - 2 minutes before actually closing the connection and giving me the results of the test.

I have registered another `server.on('stop', () => console.log('stopping'));` event listener which gets called immediately and I have logged in the module itself, the event emitter and listener are working fine and PG_CON has length 2.

**Comment by nelsonic** [comment]
How _long_ are we talking? (_seconds or **minutes**_...?) 🤔

**Comment by jay-meister** [comment]
> The test hangs for about 1 - 2 minutes before actually closing the connection and giving me the results of the test.

From what I can tell, it does close the connections instantly, but the tests still seem hang for about 2 minutes.

**Comment by jay-meister** [comment]
@SimonLab was wondering if it was something to do with the default idleTimeoutMillis property in the config.

``` js
var config = {
  user: 'foo', //env var: PGUSER
  database: 'my_db', //env var: PGDATABASE
  password: 'secret', //env var: PGPASSWORD
  host: 'localhost', // Server hosting the postgres database
  port: 5432, //env var: PGPORT
  max: 10, // max number of clients in the pool
  idleTimeoutMillis: 30000, // how long a client is allowed to remain idle before being closed
};

```
