### ISSUE TITLE
License switch

### ISSUE THREAD

**Issue by nilskassube** [dwyl/hapi-postgres-connection#24]
Hi,

unfortunately in many circumstances it is not possible to use GPL'ed code. Would it be possible to re-license the project using one of the other licenses like ISC, Apache or MIT?

Best regards and thanks for your efforts!

**Comment by iteles** [comment]
Hi @nilskassube, could you please let us know your use case? 
This shouldn't be a problem but it would be great to confirm the use case first! 😊

**Comment by nilskassube** [comment]
Hi @iteles A few of the organisations we worked for are required by their legal departments to not use any GPL'ed licensed code because they are afraid of the viral nature. And stuff like a postgres connector is definitely linked to your own code. Thanks for your efforts!

**Comment by nelsonic** [comment]
@nilskassube what is your _preferred_ license?
