### ISSUE TITLE
I keep getting this error and I don't know why

### ISSUE THREAD

**Issue by IndigoBee** [dwyl/hapi-postgres-connection#39]
I'm using your example and I keep getting this error:
![image](https://user-images.githubusercontent.com/33088396/39839569-c9d71fc0-53dc-11e8-84cc-19a22667bce6.png)

I think that this plugin is not up-to-date with the last version of hapi :/

**Comment by siarcarse** [comment]
Nope! This plugin works on hapi@16 and later.
You can use pg on hapi17 with async await.
Regards

**Comment by IndigoBee** [comment]
Okay, so I cloned the repo, added `DATABASE_URL=postgres://victor:@localhost/test` and It still crashes...
![image](https://user-images.githubusercontent.com/33088396/39868858-b46bb8ec-545b-11e8-9c9d-0724dc6768df.png)
How can I make it work?

**Comment by nelsonic** [comment]
@VictorBaudot as @siarcarse suggests, this package is only compatible with Hapi versions _below_ v17.
Is your project using Hapi v16?

**Comment by IndigoBee** [comment]
as i just downloaded the repo and installed the deps from package.json, yes I'm using Hapi v16

**Comment by nelsonic** [comment]
@VictorBaudot please try to run `npm test` on your `localhost` 
in the `hapi-postgres-connection` directory. do tests pass?

**Comment by IndigoBee** [comment]
:/ Is it because it does not find my database?
![image](https://user-images.githubusercontent.com/33088396/39871949-ba9ca720-5466-11e8-9e15-bec0f4698b19.png)

**Comment by nelsonic** [comment]
Yep. that's what it looks like ... 
You appear to be on a UNIX-based system. (Linux/Mac)
Can you _test_ your PostgreSQL connection in the terminal; run the [`pg_isready`](https://www.postgresql.org/docs/9.3/static/app-pg-isready.html) 
you should see the following output:
```
/tmp:5432 - accepting connections
```

**Comment by IndigoBee** [comment]
Yes, I'm on Linux.
I can connect to my test db with `psql -d test` so it should work...

![image](https://user-images.githubusercontent.com/33088396/39873073-3aa763bc-546a-11e8-97d7-bae8d5e84d30.png)

I tried to change my env `export DATABASE_URL=postgres://victor:@localhost/test`  multiple times with others users too but not effects

**Comment by nelsonic** [comment]
@VictorBaudot does your default postgres user _not_ have a password?
https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
e.g:
`export DATABASE_URL=postgresql://victor:password@localhost/test`

**Comment by IndigoBee** [comment]
I tried with my password too but not working either.

But it finally works.

![image](https://user-images.githubusercontent.com/33088396/39873577-a06e47b4-546b-11e8-987d-d6332f040690.png)

I followed these instructions and npm test is now working.
Thanks for your help :)
