### ISSUE TITLE
Can i update this library for hapi 19 support?

### ISSUE THREAD

**Issue by Hydrock** [dwyl/hapi-postgres-connection#41]
Can i update this library for hapi 19 support?

**Comment by nelsonic** [comment]
@Hydrock if you have time, please go for it. 💡 
you have write access to the repo. 📝 
![image](https://user-images.githubusercontent.com/194400/79668715-acb42080-81ae-11ea-9eb1-c6ea8d68aa44.png)
When you feel the Pull Request is ready please assign for review. 👍 
Thanks. ☀️

**Comment by Hydrock** [comment]
https://github.com/dwyl/hapi-postgres-connection/pull/42 new PR

**Comment by nelsonic** [comment]
PR #42 merged. ✅ 
📦 `hapi-postgres-connection@7.0.0` is now available on NPM  🚀 
Thanks again everyone! 🎉

**Comment by Hydrock** [comment]
@nelsonic thanks🤘
