### ISSUE TITLE
Problem with resolving package

### ISSUE THREAD

**Issue by Hydrock** [dwyl/hapi-postgres-connection#43]
i didn't seee this problem because had PG installed

![image](https://user-images.githubusercontent.com/20814779/80922644-2dfedc00-8d87-11ea-8a77-47ce8a5c4031.png)
![image](https://user-images.githubusercontent.com/20814779/80922660-466ef680-8d87-11ea-9757-44a3dad24a32.png)

**Comment by salzhrani** [comment]
Can you elaborate more?
