### ISSUE TITLE
The pg.client is not available in JWT validate function

### ISSUE THREAD

**Issue by rug1** [dwyl/hapi-postgres-connection#7]
at the moment the plugin only makes the postgres client available _after_ authorization...
https://github.com/dwyl/hapi-postgres-connection/blob/218aa68f7a75ab8a7dad73125663da00a309d3bb/index.js#L12

when we change `'onPreHandler'` to `'onPreAuth'` the postgres become available in the JWT `validateFunction`. can we submit a patch?

**Comment by nelsonic** [comment]
Makes sense. please PR. :+1:
